### ISSUE TITLE
Revize textů: Jsou všechna tvrzení podložená?

### ISSUE THREAD

**Issue by spacekpe** [mukrop/faktaoklimatu#18]
Ahoj,

základní myšlenka a infografiky jsou super!

Chci ale upozornit na to, že popis infografik občas sklouzne k tvrzením, která nejsou v textu doložená/doklikatelná:

Např. https://faktaoklimatu.cz/infographics/emise-1/
> Naproti tomu, zvolit si pro svou cestu ekologický způsob přepravy (tedy neletět), zateplit dům, změnit dodavatele elektřiny či výrazně omezit konzumaci masa mohu poměrně snadno, a taky celkem rychle.

V tomhle odstavci vyvstává spousta otázek o platnosti tvrzení, např. kde najdu
- srovnání emisí (na km?) letecké dopravy vs. automobilu/autobusu/vlaku?
- srovnání emisí na výrobu 1 kg hovězího/vepřového/kuřecího/sóji
- srovnání emisí na výrobu a instalaci zateplení vs. emisí při vytápění domu bez zateplení (nejspíš vztáhnout na dobu životnosti zateplení)

Mimochodem, doporučuji zdžet se výroků jako "snadno zateplit dům" atd. To může "snadno" provést jen pár procent populace ČR, která a) má vlastní dům b) má dost peněz na to, aby si mohla dovolit provést zateplení. Takhle text dělá dojem, že ho píšou lidi, kteří jsou "ve vatě" a chtějí radit všem ostatním.

**Comment by ondraspribyla** [comment]
Vlastně souhlasím... Texty jsou v zárodku a myslím že bude potřeba najít rovnováhu mezi čistým komentováním grafů a snahou ukazovat i možné cesty... Když texty zkouším psát napadají mě hromady souvislosti ale není zas dobře je tam cpat všechny... To hlavní co chci odepsat ale je "petre, vítej v týmu a dík za připomínku ;+)

**Comment by crysman** [comment]
je to alfaverze nezrevidovana

díkyze to komentujete a rozpracovavatw

--
--
Martin crysman Zahradník
== odesláno z mobilu ==
== sent from mobile phone ==

---------- Původní zpráva ----------
Od: ondraspribyla 
Datum: 6. 7. 2019 v 23:05:32
Předmět: Re: [mukrop/faktaoklimatu] doplnění podpory pro tvrzení (#18)


Vlastně souhlasím... Texty jsou v zárodku a myslím že bude potřeba najít 
rovnováhu mezi čistým komentováním grafů a snahou ukazovat i možné cesty... 
Když texty zkouším psát napadají mě hromady souvislosti ale není zas dobře 
je tam cpat všechny... To hlavní co chci odepsat ale je "petre, vítej v týmu
a dík za připomínku ;+)





—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
(https://github.com/mukrop/faktaoklimatu/issues/18?email_source=notifications&email_token=ABIGOZQHLFP5HYSGDJCV3Z3P6ECJPA5CNFSM4H6TOC22YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODZLAH2Q#issuecomment-508953578)
, or mute the thread

**Comment by mukrop** [comment]
Prerabam tento issue na celkovu reviziu textov, aby v nich boli len podlozene informacie,

**Comment by mukrop** [comment]
Ondras presiel texty, aby boli aspon zakladne ready na publikovanie. @spacekpe mozes ich prosim prejst, ci je tam nieco, co pred zverejnenim nutne potrebuje oravit? Obcasne nepodlozene tvrdenir nie je idealne, ale zatial to zvladneme a opravime v dalsej iteracii.

Ak pri tej prilezitosti objavis nieco ine, co nefunguje a malo by, urob prosim bug issue.

**Comment by spacekpe** [comment]
Myslím si, že minimálně #34 bysme měli vyřešit ještě před publikací. Na ostatní věci udělám issue nebo PR.

**Comment by spacekpe** [comment]
Jo a před releasem by to chtělo projít a buď opravit nebo schovat FIXME, např. na https://faktaoklimatu.cz/infographics/teploty-3/, ale i jinde.

**Comment by ondraspribyla** [comment]
Na této obecné úrovni je issue outdated. Texty jsou v velké většině přepsány, případné doplnění nebo korekce tvrzení budeme doplňovat v okamžiku, kdy zjistíme konkrétní nedostatek.
